try {
  a
} catch (e) {
  console.log(`Error! \n ${e}`);
}