try {
  a
} catch(err){
}
console.log('a');